### ISSUE TITLE
FR: Add TypeScript support

### ISSUE THREAD

**Issue by lorenzofiamingo** [Logan-Liffick/spltjs#1]

**Comment by loganliffick** [comment]
In the works for v2 👍

**Comment by Spikeysanju** [comment]
@loganliffick  How are you? Has there been any update on this?

**Comment by loganliffick** [comment]
@Spikeysanju 👋

Doing well, hope you are too!

Still working on a react module for splt, seems I have to take it line by line (good thing the library is small) but running into a few issues after the string is initially split.

I laid it all out [here in the WIP build on Codesandbox](https://codesandbox.io/s/splt-for-react-hq5gq) if you want to take a peek or have any thoughts for a solution. Fair warning, It gets a bit dicey when you add in line 19 and start rebuilding the text string as individual characters.

**Comment by loganliffick** [comment]
Hey @Spikeysanju and @lorenzofiamingo , well past-due for an update on V2, but it's here in the form of a [new package](https://react.spltjs.com) 🎉

Hope you've both been well ❤️

**Comment by Spikeysanju** [comment]
Great work @loganliffick 👌
